# web port
server:
  port: 9016

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    # 属性配置
    props:
      # 展示修改以后的sql语句
      sql-show: true
    # 数据源配置
    datasource:
      # 给每个数据源取别名，指定数据源名字，多个数据源之间以逗号分隔
      names: master, slave
      master:
        jdbc-url: jdbc:mysql://192.168.101.100:3307/sharding?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
        # 数据库驱动类名
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 数据库连接池类名称
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      slave:
        jdbc-url: jdbc:mysql://192.168.101.100:3308/sharding?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
        # 数据库驱动类名
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 数据库连接池类名称
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    rules:
      readwrite-splitting:
        data-sources:
          master-data-source-name: master
          slave-data-source-names: slave
mybatis:
  type-aliases-package: com.tuacy.spring.workstation.sharding.sphere.jdbc.entity.entity
  mapper-locations:  classpath*:com/tuacy/spring/workstation/sharding/sphere/jdbc/mapper/**/*.xml
